github:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - docs/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/package.json"
          - "**/pnpm-lock.yaml"
          - "**/package-lock.json"
          - "**/yarn.lock"
          - "**/bun.lockb"

source:
  - changed-files:
      - any-glob-to-any-file:
          - src/**
          - app/**
          - packages/**
